---
name: ci

on:
  push:
    branches: [add-github-actions]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        puppet_version: [6,7]

    name: Check / Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run pdk validate
        uses: markt-de/action-pdk-validate@main
        with:
          pdk-image: puppet/pdk:nightly
          puppet-version: ${{ matrix.puppet_version }}

      - name: Run pdk test unit
        uses: markt-de/action-pdk-test-unit@main
        with:
          pdk-image: puppet/pdk:nightly
          puppet-version: ${{ matrix.puppet_version }}

  acceptance:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'el8', 'rocky8' ]
        puppet_version: [6,7]

    name: Acceptance / ${{ matrix.os }} / Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-20.04
    needs:
      - check

    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Run Litmus
        env:
          DEBUG: true
        run: |
          bundle exec rake 'litmus:provision_list[gha_${{ matrix.os }}]'
          bundle exec rake 'litmus:install_agent[puppet${{ matrix.puppet_version }}]'
          bundle exec rake litmus:install_module
          bundle exec rake litmus:acceptance:parallel
      - name: Cleanup
        run: |
          bundle exec rake 'litmus:tear_down'
